### ISSUE TITLE
Yazar entryleri indirebilen versiyonu yapılabilir mi?

### ISSUE THREAD

**Issue by semihb83** [zeynepbaydemir/eksi-sozluk-veri-cekme#1]
Yazar entryleri normal entryden farklı bir formatta listelendiği için 1 sayfa algılayıp sadece son entrylerini indiriyor. Herhangi bir yazarın tüm entrylerini indirebilecek versiyonu yapılabilir mi?

**Comment by zeynepbaydemir** [comment]
https://github.com/zeynepbaydemir/eksi-sozluk-veri-cekme/blob/main/yazar.py 

Bu kodu kullanabilirsiniz.

**Comment by semihb83** [comment]
Mükemmel, elinize sağlık 🙏

**Comment by semihb83** [comment]
Tekrar merhaba, kodu başlık ve tarih de çektirecek şekilde revize etmek mümkün müdür?

**Comment by zeynepbaydemir** [comment]
https://github.com/zeynepbaydemir/eksi-sozluk-veri-cekme/blob/main/yazar.py güncellenmiş koda linkten ulaşabilirsiniz

**Comment by semihb83** [comment]
Harikasınız çok teşekkürler
